var designArray = {
 "practice": [
  {
   "runNb": "0",
   "runID": "0",
   "trialNb": "1",
   "trType": "1",
   "goalToken": "3",
   "uncertainty": "1",
   "unavAct": "3",
   "corrAct": "2",
   "bestAct": "3",
   "vertOrd": "1",
   "horizOrd": "1",
   "tokenIfLeft": "NaN",
   "tokenIfMid": "NaN",
   "tokenIfRight": "NaN"
  },
  {
   "runNb": "0",
   "runID": "0",
   "trialNb": "2",
   "trType": "1",
   "goalToken": "3",
   "uncertainty": "1",
   "unavAct": "2",
   "corrAct": "3",
   "bestAct": "3",
   "vertOrd": "1",
   "horizOrd": "1",
   "tokenIfLeft": "NaN",
   "tokenIfMid": "NaN",
   "tokenIfRight": "NaN"
  },
  {
   "runNb": "0",
   "runID": "0",
   "trialNb": "3",
   "trType": "2",
   "goalToken": "3",
   "uncertainty": "1",
   "unavAct": "2",
   "corrAct": "3",
   "bestAct": "3",
   "vertOrd": "1",
   "horizOrd": "1",
   "tokenIfLeft": "1",
   "tokenIfMid": "2",
   "tokenIfRight": "3"
  },
  {
   "runNb": "0",
   "runID": "0",
   "trialNb": "4",
   "trType": "1",
   "goalToken": "3",
   "uncertainty": "1",
   "unavAct": "1",
   "corrAct": "3",
   "bestAct": "3",
   "vertOrd": "1",
   "horizOrd": "1",
   "tokenIfLeft": "NaN",
   "tokenIfMid": "NaN",
   "tokenIfRight": "NaN"
  },
  {
   "runNb": "0",
   "runID": "0",
   "trialNb": "5",
   "trType": "1",
   "goalToken": "2",
   "uncertainty": "1",
   "unavAct": "1",
   "corrAct": "2",
   "bestAct": "2",
   "vertOrd": "1",
   "horizOrd": "1",
   "tokenIfLeft": "NaN",
   "tokenIfMid": "NaN",
   "tokenIfRight": "NaN"
  },
  {
   "runNb": "0",
   "runID": "0",
   "trialNb": "6",
   "trType": "1",
   "goalToken": "2",
   "uncertainty": "1",
   "unavAct": "2",
   "corrAct": "1",
   "bestAct": "2",
   "vertOrd": "1",
   "horizOrd": "1",
   "tokenIfLeft": "NaN",
   "tokenIfMid": "NaN",
   "tokenIfRight": "NaN"
  },
  {
   "runNb": "0",
   "runID": "0",
   "trialNb": "7",
   "trType": "2",
   "goalToken": "2",
   "uncertainty": "1",
   "unavAct": "1",
   "corrAct": "2",
   "bestAct": "2",
   "vertOrd": "1",
   "horizOrd": "1",
   "tokenIfLeft": "1",
   "tokenIfMid": "2",
   "tokenIfRight": "3"
  },
  {
   "runNb": "0",
   "runID": "0",
   "trialNb": "8",
   "trType": "1",
   "goalToken": "1",
   "uncertainty": "1",
   "unavAct": "1",
   "corrAct": "3",
   "bestAct": "1",
   "vertOrd": "1",
   "horizOrd": "1",
   "tokenIfLeft": "NaN",
   "tokenIfMid": "NaN",
   "tokenIfRight": "NaN"
  },
  {
   "runNb": "0",
   "runID": "0",
   "trialNb": "9",
   "trType": "1",
   "goalToken": "1",
   "uncertainty": "1",
   "unavAct": "3",
   "corrAct": "1",
   "bestAct": "1",
   "vertOrd": "1",
   "horizOrd": "1",
   "tokenIfLeft": "NaN",
   "tokenIfMid": "NaN",
   "tokenIfRight": "NaN"
  },
  {
   "runNb": "0",
   "runID": "0",
   "trialNb": "10",
   "trType": "2",
   "goalToken": "1",
   "uncertainty": "1",
   "unavAct": "2",
   "corrAct": "1",
   "bestAct": "1",
   "vertOrd": "1",
   "horizOrd": "1",
   "tokenIfLeft": "1",
   "tokenIfMid": "2",
   "tokenIfRight": "3"
  }
 ],
 "main": [
  [
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "1",
    "trType": "1",
    "goalToken": "1",
    "uncertainty": "1",
    "unavAct": "1",
    "corrAct": "2",
    "bestAct": "2",
    "vertOrd": "2",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "2",
    "trType": "1",
    "goalToken": "1",
    "uncertainty": "1",
    "unavAct": "2",
    "corrAct": "1",
    "bestAct": "2",
    "vertOrd": "2",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "3",
    "trType": "2",
    "goalToken": "1",
    "uncertainty": "1",
    "unavAct": "3",
    "corrAct": "2",
    "bestAct": "2",
    "vertOrd": "2",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "3",
    "tokenIfMid": "1",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "4",
    "trType": "1",
    "goalToken": "1",
    "uncertainty": "1",
    "unavAct": "2",
    "corrAct": "1",
    "bestAct": "2",
    "vertOrd": "2",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "5",
    "trType": "1",
    "goalToken": "2",
    "uncertainty": "1",
    "unavAct": "2",
    "corrAct": "3",
    "bestAct": "3",
    "vertOrd": "2",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "6",
    "trType": "2",
    "goalToken": "2",
    "uncertainty": "1",
    "unavAct": "3",
    "corrAct": "2",
    "bestAct": "3",
    "vertOrd": "2",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "1",
    "tokenIfMid": "1",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "7",
    "trType": "1",
    "goalToken": "2",
    "uncertainty": "1",
    "unavAct": "1",
    "corrAct": "3",
    "bestAct": "3",
    "vertOrd": "2",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "8",
    "trType": "1",
    "goalToken": "2",
    "uncertainty": "1",
    "unavAct": "2",
    "corrAct": "3",
    "bestAct": "3",
    "vertOrd": "2",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "9",
    "trType": "1",
    "goalToken": "1",
    "uncertainty": "1",
    "unavAct": "3",
    "corrAct": "2",
    "bestAct": "2",
    "vertOrd": "2",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "10",
    "trType": "2",
    "goalToken": "1",
    "uncertainty": "1",
    "unavAct": "1",
    "corrAct": "2",
    "bestAct": "2",
    "vertOrd": "2",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "2",
    "tokenIfRight": "3"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "11",
    "trType": "1",
    "goalToken": "1",
    "uncertainty": "1",
    "unavAct": "1",
    "corrAct": "2",
    "bestAct": "2",
    "vertOrd": "2",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "12",
    "trType": "2",
    "goalToken": "1",
    "uncertainty": "1",
    "unavAct": "1",
    "corrAct": "2",
    "bestAct": "2",
    "vertOrd": "2",
    "horizOrd": "3",
    "isBreak": "1",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "1",
    "tokenIfRight": "2"
   },
   {
    "runNb": "2",
    "runID": "2",
    "trialNb": "1",
    "trType": "1",
    "goalToken": "3",
    "uncertainty": "2",
    "unavAct": "2",
    "corrAct": "3",
    "bestAct": "3",
    "vertOrd": "3",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "2",
    "runID": "2",
    "trialNb": "2",
    "trType": "1",
    "goalToken": "3",
    "uncertainty": "2",
    "unavAct": "3",
    "corrAct": "2",
    "bestAct": "3",
    "vertOrd": "3",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "2",
    "runID": "2",
    "trialNb": "3",
    "trType": "2",
    "goalToken": "3",
    "uncertainty": "2",
    "unavAct": "1",
    "corrAct": "3",
    "bestAct": "3",
    "vertOrd": "3",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "3",
    "tokenIfRight": "3"
   },
   {
    "runNb": "2",
    "runID": "2",
    "trialNb": "4",
    "trType": "1",
    "goalToken": "3",
    "uncertainty": "2",
    "unavAct": "1",
    "corrAct": "3",
    "bestAct": "3",
    "vertOrd": "3",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "2",
    "runID": "2",
    "trialNb": "5",
    "trType": "1",
    "goalToken": "3",
    "uncertainty": "2",
    "unavAct": "3",
    "corrAct": "2",
    "bestAct": "3",
    "vertOrd": "3",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "2",
    "runID": "2",
    "trialNb": "6",
    "trType": "1",
    "goalToken": "1",
    "uncertainty": "2",
    "unavAct": "3",
    "corrAct": "1",
    "bestAct": "1",
    "vertOrd": "3",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "2",
    "runID": "2",
    "trialNb": "7",
    "trType": "2",
    "goalToken": "1",
    "uncertainty": "2",
    "unavAct": "1",
    "corrAct": "3",
    "bestAct": "1",
    "vertOrd": "3",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "1",
    "tokenIfRight": "2"
   },
   {
    "runNb": "2",
    "runID": "2",
    "trialNb": "8",
    "trType": "1",
    "goalToken": "1",
    "uncertainty": "2",
    "unavAct": "3",
    "corrAct": "1",
    "bestAct": "1",
    "vertOrd": "3",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "2",
    "runID": "2",
    "trialNb": "9",
    "trType": "1",
    "goalToken": "2",
    "uncertainty": "2",
    "unavAct": "3",
    "corrAct": "2",
    "bestAct": "2",
    "vertOrd": "3",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "2",
    "runID": "2",
    "trialNb": "10",
    "trType": "2",
    "goalToken": "2",
    "uncertainty": "2",
    "unavAct": "2",
    "corrAct": "1",
    "bestAct": "2",
    "vertOrd": "3",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "2",
    "tokenIfMid": "NaN",
    "tokenIfRight": "3"
   },
   {
    "runNb": "2",
    "runID": "2",
    "trialNb": "11",
    "trType": "1",
    "goalToken": "2",
    "uncertainty": "2",
    "unavAct": "1",
    "corrAct": "2",
    "bestAct": "2",
    "vertOrd": "3",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "2",
    "runID": "2",
    "trialNb": "12",
    "trType": "2",
    "goalToken": "2",
    "uncertainty": "2",
    "unavAct": "3",
    "corrAct": "2",
    "bestAct": "2",
    "vertOrd": "3",
    "horizOrd": "1",
    "isBreak": "1",
    "tokenIfLeft": "1",
    "tokenIfMid": "1",
    "tokenIfRight": "NaN"
   }
  ],
  [
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "1",
    "trType": "1",
    "goalToken": "2",
    "uncertainty": "2",
    "unavAct": "2",
    "corrAct": "3",
    "bestAct": "3",
    "vertOrd": "1",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "2",
    "trType": "1",
    "goalToken": "2",
    "uncertainty": "2",
    "unavAct": "3",
    "corrAct": "2",
    "bestAct": "3",
    "vertOrd": "1",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "3",
    "trType": "2",
    "goalToken": "2",
    "uncertainty": "2",
    "unavAct": "1",
    "corrAct": "3",
    "bestAct": "3",
    "vertOrd": "1",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "2",
    "tokenIfRight": "2"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "4",
    "trType": "1",
    "goalToken": "2",
    "uncertainty": "2",
    "unavAct": "3",
    "corrAct": "2",
    "bestAct": "3",
    "vertOrd": "1",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "5",
    "trType": "1",
    "goalToken": "3",
    "uncertainty": "2",
    "unavAct": "3",
    "corrAct": "1",
    "bestAct": "1",
    "vertOrd": "1",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "6",
    "trType": "2",
    "goalToken": "3",
    "uncertainty": "2",
    "unavAct": "1",
    "corrAct": "3",
    "bestAct": "1",
    "vertOrd": "1",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "2",
    "tokenIfRight": "2"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "7",
    "trType": "1",
    "goalToken": "3",
    "uncertainty": "2",
    "unavAct": "2",
    "corrAct": "1",
    "bestAct": "1",
    "vertOrd": "1",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "8",
    "trType": "1",
    "goalToken": "3",
    "uncertainty": "2",
    "unavAct": "3",
    "corrAct": "1",
    "bestAct": "1",
    "vertOrd": "1",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "9",
    "trType": "1",
    "goalToken": "2",
    "uncertainty": "2",
    "unavAct": "1",
    "corrAct": "3",
    "bestAct": "3",
    "vertOrd": "1",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "10",
    "trType": "2",
    "goalToken": "2",
    "uncertainty": "2",
    "unavAct": "2",
    "corrAct": "3",
    "bestAct": "3",
    "vertOrd": "1",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "3",
    "tokenIfMid": "NaN",
    "tokenIfRight": "1"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "11",
    "trType": "1",
    "goalToken": "2",
    "uncertainty": "2",
    "unavAct": "2",
    "corrAct": "3",
    "bestAct": "3",
    "vertOrd": "1",
    "horizOrd": "3",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "1",
    "runID": "1",
    "trialNb": "12",
    "trType": "2",
    "goalToken": "2",
    "uncertainty": "2",
    "unavAct": "2",
    "corrAct": "3",
    "bestAct": "3",
    "vertOrd": "1",
    "horizOrd": "3",
    "isBreak": "1",
    "tokenIfLeft": "2",
    "tokenIfMid": "NaN",
    "tokenIfRight": "2"
   },
   {
    "runNb": "2",
    "runID": "4",
    "trialNb": "1",
    "trType": "1",
    "goalToken": "2",
    "uncertainty": "1",
    "unavAct": "3",
    "corrAct": "2",
    "bestAct": "2",
    "vertOrd": "2",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "2",
    "runID": "4",
    "trialNb": "2",
    "trType": "2",
    "goalToken": "2",
    "uncertainty": "1",
    "unavAct": "1",
    "corrAct": "2",
    "bestAct": "2",
    "vertOrd": "2",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "2",
    "tokenIfRight": "2"
   },
   {
    "runNb": "2",
    "runID": "4",
    "trialNb": "3",
    "trType": "1",
    "goalToken": "2",
    "uncertainty": "1",
    "unavAct": "1",
    "corrAct": "2",
    "bestAct": "2",
    "vertOrd": "2",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "2",
    "runID": "4",
    "trialNb": "4",
    "trType": "1",
    "goalToken": "1",
    "uncertainty": "1",
    "unavAct": "2",
    "corrAct": "1",
    "bestAct": "1",
    "vertOrd": "2",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "2",
    "runID": "4",
    "trialNb": "5",
    "trType": "2",
    "goalToken": "1",
    "uncertainty": "1",
    "unavAct": "3",
    "corrAct": "1",
    "bestAct": "1",
    "vertOrd": "2",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "2",
    "tokenIfMid": "2",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "2",
    "runID": "4",
    "trialNb": "6",
    "trType": "1",
    "goalToken": "1",
    "uncertainty": "1",
    "unavAct": "3",
    "corrAct": "1",
    "bestAct": "1",
    "vertOrd": "2",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "2",
    "runID": "4",
    "trialNb": "7",
    "trType": "1",
    "goalToken": "3",
    "uncertainty": "1",
    "unavAct": "2",
    "corrAct": "3",
    "bestAct": "3",
    "vertOrd": "2",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "2",
    "runID": "4",
    "trialNb": "8",
    "trType": "1",
    "goalToken": "3",
    "uncertainty": "1",
    "unavAct": "3",
    "corrAct": "2",
    "bestAct": "3",
    "vertOrd": "2",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "2",
    "runID": "4",
    "trialNb": "9",
    "trType": "2",
    "goalToken": "3",
    "uncertainty": "1",
    "unavAct": "1",
    "corrAct": "3",
    "bestAct": "3",
    "vertOrd": "2",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "2",
    "tokenIfRight": "3"
   },
   {
    "runNb": "2",
    "runID": "4",
    "trialNb": "10",
    "trType": "1",
    "goalToken": "3",
    "uncertainty": "1",
    "unavAct": "2",
    "corrAct": "3",
    "bestAct": "3",
    "vertOrd": "2",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "2",
    "runID": "4",
    "trialNb": "11",
    "trType": "1",
    "goalToken": "1",
    "uncertainty": "1",
    "unavAct": "2",
    "corrAct": "1",
    "bestAct": "1",
    "vertOrd": "2",
    "horizOrd": "1",
    "isBreak": "0",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "NaN",
    "tokenIfRight": "NaN"
   },
   {
    "runNb": "2",
    "runID": "4",
    "trialNb": "12",
    "trType": "2",
    "goalToken": "1",
    "uncertainty": "1",
    "unavAct": "1",
    "corrAct": "3",
    "bestAct": "1",
    "vertOrd": "2",
    "horizOrd": "1",
    "isBreak": "1",
    "tokenIfLeft": "NaN",
    "tokenIfMid": "2",
    "tokenIfRight": "3"
   }
  ]
 ]
};
